CREATE TABLE Discount
(
Discount_ID INT PRIMARY KEY IDENTITY,
Dicount_Type VARCHAR(20) NOT NULL DEFAULT 0
)

CREATE TABLE PromoCode 
(
Promo_ID INT PRIMARY KEY IDENTITY,
Discount_ID INT FOREIGN KEY REFERENCES Discount (Discount_ID) ON DELETE CASCADE,
Code VARCHAR(20),
[Description] VARCHAR(120),
Discount_Value FLOAT NOT NULL DEFAULT 0
)

CREATE TABLE RoomCategory 
(
Category_ID INT PRIMARY KEY IDENTITY,
[Description] VARCHAR(120),
Price FLOAT NOT NULL DEFAULT 0
)

CREATE TABLE Room 
(
Room_ID INT PRIMARY KEY IDENTITY,
Category_ID INT FOREIGN KEY REFERENCES RoomCategory (Category_ID) ON DELETE CASCADE,
Room_Number TINYINT NULL,
Capacity INT NOT NULL DEFAULT 0,
[Description] VARCHAR(150),
Photo VARCHAR(220)
)

CREATE TABLE News 
(
News_ID INT PRIMARY KEY IDENTITY,
Title VARCHAR(20),
Content VARCHAR(120),
[Image] VARCHAR(220),
[Date] DATE
)

CREATE TABLE Vacancy 
(
Vacancy_ID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(20),
[Description] VARCHAR(120),
Need VARCHAR(220)
)

CREATE TABLE About 
(
About_ID INT PRIMARY KEY IDENTITY,
[Description] VARCHAR(120),
Video VARCHAR(120),
[Image] VARCHAR(220),
History VARCHAR(120),
Details VARCHAR(120),
[Certificate] VARCHAR(120)
)

CREATE TABLE [User] 
(
[User_ID] INT PRIMARY KEY IDENTITY,
[User_Name] VARCHAR(50),
[Password] VARCHAR(60),
Age INT NOT NULL DEFAULT 18,
Email VARCHAR(80)
)

CREATE TABLE [Action]
(
[Action_ID] INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(20)
)

CREATE TABLE [Data]
(
Data_ID INT PRIMARY KEY IDENTITY,
Table_Name VARCHAR(20)
)

CREATE TABLE Client
(
Client_ID INT PRIMARY KEY IDENTITY,
[User_ID] INT FOREIGN KEY REFERENCES [User] ([User_ID]) ON DELETE CASCADE,
First_Name VARCHAR(30),
Last_Name VARCHAR(20),
Patronymic VARCHAR(30),
Notes VARCHAR(120),
Phone_Number VARCHAR(20),
Has_Child TINYINT
)

CREATE TABLE CRUD
(
CRUD_ID INT PRIMARY KEY IDENTITY,
Client NVARCHAR(120) NULL,
Action_ID INT FOREIGN KEY REFERENCES [Action] (Action_ID) ON DELETE CASCADE,
Data_ID INT FOREIGN KEY REFERENCES [Data] (Data_ID) ON DELETE CASCADE,
[Date] DATE
)

CREATE TABLE Contact
(
Contact_ID INT PRIMARY KEY IDENTITY,
[User_ID] INT FOREIGN KEY REFERENCES [User] ([User_ID]) ON DELETE CASCADE,
First_Name VARCHAR(30),
Last_Name VARCHAR(20),
Patronymic VARCHAR(30),
[Description] VARCHAR(120),
Photo VARCHAR(220)
)

CREATE TABLE Position
(
Position_ID INT PRIMARY KEY IDENTITY,
Position_Name VARCHAR(20)
)

CREATE TABLE EmployeePosition
(
Employee_ID INT FOREIGN KEY REFERENCES Contact (Contact_ID) ON DELETE SET NULL NULL,
Position_ID INT FOREIGN KEY REFERENCES Position (Position_ID) ON DELETE SET NULL NULL
)

CREATE TABLE Reservation
(
Reservation_ID INT PRIMARY KEY IDENTITY,
Client_ID INT FOREIGN KEY REFERENCES Client (Client_ID) ON DELETE NO ACTION,
Promo_ID INT FOREIGN KEY REFERENCES PromoCode (Promo_ID) ON DELETE SET NULL NULL,
Room_ID INT FOREIGN KEY REFERENCES Room (Room_ID) ON DELETE SET NULL NULL,
Arrival_Date DATE,
Departure_Date DATE,
Final_Price FLOAT NOT NULL DEFAULT 0,
Created_At DATE,
Notes VARCHAR(120)
)

CREATE TABLE Payment 
(
Payment_ID INT PRIMARY KEY IDENTITY,
Reservation_ID INT FOREIGN KEY REFERENCES Reservation (Reservation_ID) ON DELETE NO ACTION,
Amount FLOAT NOT NULL DEFAULT 0,
is_completed TINYINT,
Payment_Date DATE
)